# Generated by Django 4.1.5 on 2023-02-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketing',
            options={'verbose_name': 'Baner Marketingowy', 'verbose_name_plural': 'Banery Marketingowe'},
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='firstCaption',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='firstLabel',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='firstSlide',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='secondCaption',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='secondLabel',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='secondSlide',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='thirdCaption',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='thirdLabel',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='thirdSlide',
        ),
        migrations.AddField(
            model_name='marketing',
            name='Caption',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tekst slajdu'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='Label',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tytuł slajdu'),
        ),
        migrations.AddField(
            model_name='marketing',
            name='Slide',
            field=models.FileField(blank=True, null=True, upload_to='marketing', verbose_name='Grafika slajdu'),
        ),
    ]
