# Generated by Django 4.1.5 on 2023-02-08 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='slide',
            field=models.FileField(blank=True, null=True, upload_to='marketing', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'img'])], verbose_name='Grafika slajdu'),
        ),
    ]
