# Generated by Django 4.1.5 on 2023-02-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_marketing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='Slide',
            field=models.FileField(default='settings.MEDIA_ROOT/grafika 1.png', upload_to='marketing', verbose_name='Grafika slajdu'),
        ),
    ]
