# Generated by Django 4.1.5 on 2023-02-08 20:16

import django.core.validators
from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_marketing_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='slide',
            field=models.FileField(blank=True, null=True, upload_to='marketing', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'img']), marketing.models.validate_image_height], verbose_name='Grafika slajdu'),
        ),
    ]
