# Generated by Django 4.1.5 on 2023-02-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_marketing_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketing',
            old_name='Caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='marketing',
            old_name='Label',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='Slide',
        ),
        migrations.AddField(
            model_name='marketing',
            name='slide',
            field=models.FileField(default='/default_slide.png', upload_to='marketing', verbose_name='Grafika slajdu'),
        ),
    ]
