# Generated by Django 4.1.5 on 2023-02-08 20:40

from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_alter_marketing_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='slide',
            field=models.FileField(blank=True, null=True, upload_to='marketing', validators=[marketing.models.CustomFileExtensionValidator(allowed_extensions=['png', 'jpg']), marketing.models.validate_image_height], verbose_name='Grafika slajdu'),
        ),
    ]
