# Generated by Django 4.1.5 on 2023-01-19 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderTag', models.CharField(max_length=15, verbose_name='WZP')),
                ('orderCompany', models.CharField(max_length=15, verbose_name='Firma')),
                ('orderName', models.CharField(max_length=15, verbose_name='Produkt')),
                ('orderQuantity', models.IntegerField(verbose_name='Ilość')),
                ('orderDate', models.DateTimeField(auto_now=True, verbose_name='Data Utworzenia')),
                ('orderManual', models.BooleanField(default=False)),
                ('orderVideo', models.BooleanField(default=False)),
                ('orderStatus', models.CharField(choices=[('pending', 'Zlecone'), ('in_progress', 'Podjęte'), ('Zakończone', 'Zakończone')], default='pending', max_length=20)),
                ('orderManager', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Autor Zlecenia')),
            ],
            options={
                'verbose_name': 'Zlecenie',
                'verbose_name_plural': 'Zlecenia',
            },
        ),
    ]
