# Generated by Django 4.1.5 on 2023-02-11 22:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderTag', models.CharField(max_length=15, verbose_name='WZP')),
                ('orderCompany', models.CharField(max_length=25, verbose_name='Firma')),
                ('orderName', models.CharField(max_length=25, verbose_name='Produkt')),
                ('orderQuantity', models.IntegerField(verbose_name='Ilość')),
                ('orderDate', models.DateTimeField(auto_now=True, verbose_name='Data Utworzenia')),
                ('orderManual', models.BooleanField(default=False)),
                ('orderVideo', models.BooleanField(default=False)),
                ('orderStatus', models.CharField(choices=[('Zlecone', 'Zlecone'), ('Podjęte', 'Podjęte'), ('Zakończone', 'Zakończone')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Instrukcja I')),
                ('fileLanguage', models.CharField(blank=True, max_length=20, null=True, verbose_name='Język instrukcji I')),
                ('file2', models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Instrukcja II')),
                ('file2Language', models.CharField(blank=True, max_length=20, null=True, verbose_name='Język instrukcji II')),
                ('file3', models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Instrukcja III')),
                ('file3Language', models.CharField(blank=True, max_length=20, null=True, verbose_name='Język instrukcji III')),
                ('file4', models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Instrukcja IV')),
                ('file4Language', models.CharField(blank=True, max_length=20, null=True, verbose_name='Język instrukcji IV')),
                ('url', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('video', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Multimedia/Video Embed')),
                ('orderManager', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Autor Zlecenia')),
            ],
            options={
                'verbose_name': 'Zlecenie',
                'verbose_name_plural': 'Zlecenia',
            },
        ),
    ]
