# Generated by Django 4.1.5 on 2023-02-12 19:59

import django.core.validators
from django.db import migrations, models
import qr.validators


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[qr.validators.validate_file_size, django.core.validators.FileExtensionValidator(['pdf'], message='Plik musi mieć format PDF')], verbose_name='Instrukcja I'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[qr.validators.validate_file_size, django.core.validators.FileExtensionValidator(['pdf'], message='Plik musi mieć format PDF')], verbose_name='Instrukcja II'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[qr.validators.validate_file_size, django.core.validators.FileExtensionValidator(['pdf'], message='Plik musi mieć format PDF')], verbose_name='Instrukcja III'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[qr.validators.validate_file_size, django.core.validators.FileExtensionValidator(['pdf'], message='Plik musi mieć format PDF')], verbose_name='Instrukcja IV'),
        ),
    ]
