# Generated by Django 4.1.5 on 2023-01-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_rename_orderfile_order_file_order_url_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Plik'),
        ),
    ]
