# Generated by Django 4.1.5 on 2023-02-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_alter_order_file_alter_order_file2_alter_order_file3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderCompany',
            field=models.CharField(max_length=30, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderName',
            field=models.CharField(max_length=30, verbose_name='Produkt'),
        ),
    ]
