# Generated by Django 4.1.5 on 2023-02-20 20:31

from django.db import migrations, models
import qr.validators


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_alter_order_ordercompany_alter_order_ordername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='manual/', validators=[qr.validators.validate_file_size, qr.validators.validate_pdf], verbose_name='Instrukcja I'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='manual/', validators=[qr.validators.validate_file_size, qr.validators.validate_pdf], verbose_name='Instrukcja II'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='manual/', validators=[qr.validators.validate_file_size, qr.validators.validate_pdf], verbose_name='Instrukcja III'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='manual/', validators=[qr.validators.validate_file_size, qr.validators.validate_pdf], verbose_name='Instrukcja IV'),
        ),
    ]
