# Generated by Django 4.1.5 on 2023-01-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0005_alter_order_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('Zlecone', 'Zlecone'), ('Podjęte', 'Podjęte'), ('Zakończone', 'Zakończone')], default='pending', max_length=20),
        ),
    ]
