# Generated by Django 4.1.5 on 2023-02-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0006_alter_order_ordercompany_alter_order_ordername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderTag',
            field=models.CharField(max_length=18, unique=True, verbose_name='WZP'),
        ),
    ]
