# Generated by Django 4.1.5 on 2023-01-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0006_alter_order_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('Zlecone', 'Zlecone'), ('Podjęte', 'Podjęte'), ('Zakończone', 'Zakończone')], max_length=20),
        ),
    ]
