# Generated by Django 4.1.5 on 2023-05-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0007_alter_order_ordertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderCompany',
            field=models.CharField(max_length=40, verbose_name='Klient'),
        ),
    ]
