# Generated by Django 4.1.5 on 2023-05-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0007_alter_order_ordertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file2_downloads',
            field=models.IntegerField(default=0, verbose_name='#2Downloaded'),
        ),
        migrations.AddField(
            model_name='order',
            name='file3_downloads',
            field=models.IntegerField(default=0, verbose_name='#3Downloaded'),
        ),
        migrations.AddField(
            model_name='order',
            name='file4_downloads',
            field=models.IntegerField(default=0, verbose_name='#4Downloaded'),
        ),
        migrations.AddField(
            model_name='order',
            name='file_downloads',
            field=models.IntegerField(default=0, verbose_name='#1Downloaded'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderCompany',
            field=models.CharField(max_length=40, verbose_name='Klient'),
        ),
    ]
