# Generated by Django 4.1.5 on 2023-05-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0008_order_file2_downloads_order_file3_downloads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(blank=True, choices=[('Zlecone', 'Zlecone'), ('Podjęte', 'Podjęte'), ('Zakończone', 'Zakończone')], max_length=20, null=True),
        ),
    ]
