# Generated by Django 4.1.5 on 2023-05-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0008_alter_order_ordercompany'),
        ('qr', '0008_order_file2_downloads_order_file3_downloads_and_more'),
    ]

    operations = [
    ]
