# Generated by Django 4.1.5 on 2023-01-23 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0009_alter_order_file_alter_order_file2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Instrukcja PL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Instrukcja ENG'),
        ),
    ]
