# Generated by Django 4.1.5 on 2023-01-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0010_alter_order_file_alter_order_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='video',
            field=models.URLField(blank=True, max_length=600, verbose_name='Instrukcja Multimedialna'),
        ),
    ]
