# Generated by Django 4.1.5 on 2023-01-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0011_order_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='video',
            field=models.TextField(max_length=10000, verbose_name='Multimedia/Video Embed'),
        ),
    ]
