# Generated by Django 4.1.5 on 2023-01-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0013_alter_order_ordercompany_alter_order_ordername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='video',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Multimedia/Video Embed'),
        ),
    ]
