# Generated by Django 4.1.5 on 2023-01-31 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0014_alter_order_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file2Language',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Język instrukcji II'),
        ),
        migrations.AddField(
            model_name='order',
            name='fileLanguage',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Język instrukcji I'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Instrukcja I'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Instrukcja II'),
        ),
    ]
