# Generated by Django 4.1.5 on 2023-02-05 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0016_marketin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marketin',
            new_name='Marketing',
        ),
    ]
