# Generated by Django 4.1.5 on 2023-02-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0017_rename_marketin_marketing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marketing',
        ),
    ]
